import type { ExcelColumnConfig, ExcelExportOptions } from '~/shared/types'

export interface ExcelExportPreset {
  id: string
  name: string
  description: string
  isSystem: boolean
  columns: ExcelColumnConfig[]
  options: ExcelExportOptions
}

export const systemPresets: ExcelExportPreset[] = [
  {
    id: 'standard',
    name: 'Standard Bibliography',
    description: 'Essential fields for a clean bibliography view',
    isSystem: true,
    columns: [
      {
        id: 'title',
        field: 'title',
        header: 'Title',
        width: 50,
        format: 'text',
        enabled: true,
        order: 1,
      },
      {
        id: 'authors',
        field: 'authors',
        header: 'Authors',
        width: 30,
        format: 'author_format',
        enabled: true,
        order: 2,
      },
      {
        id: 'year',
        field: 'year',
        header: 'Year',
        width: 10,
        format: 'number',
        enabled: true,
        order: 3,
      },
      {
        id: 'type',
        field: 'entryType',
        header: 'Type',
        width: 15,
        format: 'text',
        enabled: true,
        order: 4,
      },
      {
        id: 'publisher',
        field: 'metadata.publisher',
        header: 'Publisher',
        width: 25,
        format: 'text',
        enabled: true,
        order: 5,
      },
      {
        id: 'doi',
        field: 'metadata.doi',
        header: 'DOI',
        width: 30,
        format: 'hyperlink',
        enabled: true,
        order: 6,
      },
      {
        id: 'tags',
        field: 'tags',
        header: 'Tags',
        width: 25,
        format: 'comma_separated',
        enabled: true,
        order: 7,
      },
    ],
    options: {
      includeHeaderRow: true,
      freezeHeaderRow: true,
      autoFitColumns: true,
      alternateRowColors: true,
      enableWrapping: false,
      headerStyle: { bold: true, backgroundColor: '#4F46E5', textColor: '#FFFFFF', fontSize: 11 },
      sortBy: [{ field: 'authors', direction: 'asc' }],
      filters: {},
      additionalSheets: {
        summary: false,
        tagBreakdown: false,
        sourceTypeDistribution: false,
        veritasDistribution: false,
        timelineChart: false,
      },
    },
  },
  {
    id: 'annotated',
    name: 'Annotated Bibliography',
    description: 'Full bibliography with annotations for research review',
    isSystem: true,
    columns: [
      {
        id: 'title',
        field: 'title',
        header: 'Title',
        width: 40,
        format: 'text',
        enabled: true,
        order: 1,
      },
      {
        id: 'authors',
        field: 'authors',
        header: 'Authors',
        width: 25,
        format: 'author_format',
        enabled: true,
        order: 2,
      },
      {
        id: 'year',
        field: 'year',
        header: 'Year',
        width: 8,
        format: 'number',
        enabled: true,
        order: 3,
      },
      {
        id: 'type',
        field: 'entryType',
        header: 'Type',
        width: 12,
        format: 'text',
        enabled: true,
        order: 4,
      },
      {
        id: 'publisher',
        field: 'metadata.publisher',
        header: 'Publisher',
        width: 20,
        format: 'text',
        enabled: true,
        order: 5,
      },
      {
        id: 'annotation',
        field: 'annotations_all_content',
        header: 'Annotations',
        width: 80,
        format: 'text_wrap',
        enabled: true,
        order: 6,
      },
      {
        id: 'annotationType',
        field: 'annotations_all_types',
        header: 'Annotation Types',
        width: 20,
        format: 'text',
        enabled: true,
        order: 7,
      },
      {
        id: 'tags',
        field: 'tags',
        header: 'Tags',
        width: 20,
        format: 'comma_separated',
        enabled: true,
        order: 8,
      },
    ],
    options: {
      includeHeaderRow: true,
      freezeHeaderRow: true,
      autoFitColumns: false,
      alternateRowColors: true,
      enableWrapping: true,
      headerStyle: { bold: true, backgroundColor: '#059669', textColor: '#FFFFFF', fontSize: 11 },
      sortBy: [{ field: 'authors', direction: 'asc' }],
      filters: {},
      additionalSheets: {
        summary: false,
        tagBreakdown: false,
        sourceTypeDistribution: false,
        veritasDistribution: false,
        timelineChart: false,
      },
    },
  },
  {
    id: 'research-analysis',
    name: 'Research Analysis',
    description: 'Comprehensive view with credibility scores and metadata for analysis',
    isSystem: true,
    columns: [
      {
        id: 'title',
        field: 'title',
        header: 'Title',
        width: 40,
        format: 'text',
        enabled: true,
        order: 1,
      },
      {
        id: 'authors',
        field: 'authors',
        header: 'Authors',
        width: 25,
        format: 'author_format',
        enabled: true,
        order: 2,
      },
      {
        id: 'year',
        field: 'year',
        header: 'Year',
        width: 8,
        format: 'number',
        enabled: true,
        order: 3,
      },
      {
        id: 'type',
        field: 'entryType',
        header: 'Type',
        width: 12,
        format: 'text',
        enabled: true,
        order: 4,
      },
      {
        id: 'journal',
        field: 'metadata.journal',
        header: 'Journal',
        width: 25,
        format: 'text',
        enabled: true,
        order: 5,
      },
      {
        id: 'veritas',
        field: 'veritasScore.overallScore',
        header: 'Veritas Score',
        width: 12,
        format: 'veritas_score',
        enabled: true,
        order: 6,
      },
      {
        id: 'citations',
        field: 'metadata.citationCount',
        header: 'Citations',
        width: 10,
        format: 'number',
        enabled: true,
        order: 7,
      },
      {
        id: 'doi',
        field: 'metadata.doi',
        header: 'DOI',
        width: 25,
        format: 'hyperlink',
        enabled: true,
        order: 8,
      },
      {
        id: 'abstract',
        field: 'metadata.abstract',
        header: 'Abstract',
        width: 60,
        format: 'text_wrap',
        enabled: true,
        order: 9,
      },
      {
        id: 'tags',
        field: 'tags',
        header: 'Tags',
        width: 20,
        format: 'comma_separated',
        enabled: true,
        order: 10,
      },
    ],
    options: {
      includeHeaderRow: true,
      freezeHeaderRow: true,
      autoFitColumns: false,
      alternateRowColors: true,
      enableWrapping: true,
      headerStyle: { bold: true, backgroundColor: '#7C3AED', textColor: '#FFFFFF', fontSize: 11 },
      sortBy: [{ field: 'veritasScore.overallScore', direction: 'desc' }],
      filters: {},
      additionalSheets: {
        summary: true,
        tagBreakdown: true,
        sourceTypeDistribution: true,
        veritasDistribution: true,
        timelineChart: false,
      },
    },
  },
  {
    id: 'journal-articles',
    name: 'Journal Articles',
    description: 'Optimized for academic journal article tracking',
    isSystem: true,
    columns: [
      {
        id: 'title',
        field: 'title',
        header: 'Article Title',
        width: 45,
        format: 'text',
        enabled: true,
        order: 1,
      },
      {
        id: 'authors',
        field: 'authors',
        header: 'Authors',
        width: 30,
        format: 'author_format',
        enabled: true,
        order: 2,
      },
      {
        id: 'year',
        field: 'year',
        header: 'Year',
        width: 8,
        format: 'number',
        enabled: true,
        order: 3,
      },
      {
        id: 'journal',
        field: 'metadata.journal',
        header: 'Journal',
        width: 30,
        format: 'text',
        enabled: true,
        order: 4,
      },
      {
        id: 'volume',
        field: 'metadata.volume',
        header: 'Vol',
        width: 6,
        format: 'text',
        enabled: true,
        order: 5,
      },
      {
        id: 'issue',
        field: 'metadata.issue',
        header: 'Issue',
        width: 6,
        format: 'text',
        enabled: true,
        order: 6,
      },
      {
        id: 'pages',
        field: 'metadata.pages',
        header: 'Pages',
        width: 12,
        format: 'text',
        enabled: true,
        order: 7,
      },
      {
        id: 'doi',
        field: 'metadata.doi',
        header: 'DOI',
        width: 30,
        format: 'hyperlink',
        enabled: true,
        order: 8,
      },
    ],
    options: {
      includeHeaderRow: true,
      freezeHeaderRow: true,
      autoFitColumns: true,
      alternateRowColors: true,
      enableWrapping: false,
      headerStyle: { bold: true, backgroundColor: '#DC2626', textColor: '#FFFFFF', fontSize: 11 },
      sortBy: [
        { field: 'metadata.journal', direction: 'asc' },
        { field: 'year', direction: 'desc' },
      ],
      filters: { entryTypes: ['journal_article'] },
      additionalSheets: {
        summary: false,
        tagBreakdown: false,
        sourceTypeDistribution: false,
        veritasDistribution: false,
        timelineChart: false,
      },
    },
  },
  {
    id: 'data-export',
    name: 'Full Data Export',
    description: 'All fields for backup or migration purposes',
    isSystem: true,
    columns: [
      { id: 'id', field: 'id', header: 'ID', width: 36, format: 'text', enabled: true, order: 1 },
      {
        id: 'title',
        field: 'title',
        header: 'Title',
        width: 40,
        format: 'text',
        enabled: true,
        order: 2,
      },
      {
        id: 'authors',
        field: 'authors',
        header: 'Authors (JSON)',
        width: 40,
        format: 'text',
        enabled: true,
        order: 3,
      },
      {
        id: 'year',
        field: 'year',
        header: 'Year',
        width: 8,
        format: 'number',
        enabled: true,
        order: 4,
      },
      {
        id: 'type',
        field: 'entryType',
        header: 'Type',
        width: 15,
        format: 'text',
        enabled: true,
        order: 5,
      },
      {
        id: 'metadata',
        field: 'metadata',
        header: 'Metadata (JSON)',
        width: 60,
        format: 'text',
        enabled: true,
        order: 6,
      },
      {
        id: 'tags',
        field: 'tags',
        header: 'Tags (JSON)',
        width: 30,
        format: 'text',
        enabled: true,
        order: 7,
      },
      {
        id: 'createdAt',
        field: 'createdAt',
        header: 'Created',
        width: 20,
        format: 'date_time',
        enabled: true,
        order: 8,
      },
      {
        id: 'updatedAt',
        field: 'updatedAt',
        header: 'Updated',
        width: 20,
        format: 'date_time',
        enabled: true,
        order: 9,
      },
    ],
    options: {
      includeHeaderRow: true,
      freezeHeaderRow: true,
      autoFitColumns: false,
      alternateRowColors: false,
      enableWrapping: false,
      headerStyle: { bold: true, backgroundColor: '#6B7280', textColor: '#FFFFFF', fontSize: 11 },
      sortBy: [{ field: 'createdAt', direction: 'asc' }],
      filters: {},
      additionalSheets: {
        summary: false,
        tagBreakdown: false,
        sourceTypeDistribution: false,
        veritasDistribution: false,
        timelineChart: false,
      },
    },
  },
]

export const allAvailableColumns: ExcelColumnConfig[] = [
  { id: 'id', field: 'id', header: 'ID', width: 36, format: 'text', enabled: false, order: 0 },
  {
    id: 'title',
    field: 'title',
    header: 'Title',
    width: 50,
    format: 'text',
    enabled: true,
    order: 1,
  },
  {
    id: 'authors',
    field: 'authors',
    header: 'Authors',
    width: 30,
    format: 'author_format',
    enabled: true,
    order: 2,
  },
  {
    id: 'year',
    field: 'year',
    header: 'Year',
    width: 10,
    format: 'number',
    enabled: true,
    order: 3,
  },
  {
    id: 'type',
    field: 'entryType',
    header: 'Entry Type',
    width: 15,
    format: 'text',
    enabled: true,
    order: 4,
  },
  {
    id: 'publisher',
    field: 'metadata.publisher',
    header: 'Publisher',
    width: 25,
    format: 'text',
    enabled: false,
    order: 5,
  },
  {
    id: 'journal',
    field: 'metadata.journal',
    header: 'Journal',
    width: 25,
    format: 'text',
    enabled: false,
    order: 6,
  },
  {
    id: 'volume',
    field: 'metadata.volume',
    header: 'Volume',
    width: 10,
    format: 'text',
    enabled: false,
    order: 7,
  },
  {
    id: 'issue',
    field: 'metadata.issue',
    header: 'Issue',
    width: 10,
    format: 'text',
    enabled: false,
    order: 8,
  },
  {
    id: 'pages',
    field: 'metadata.pages',
    header: 'Pages',
    width: 15,
    format: 'text',
    enabled: false,
    order: 9,
  },
  {
    id: 'doi',
    field: 'metadata.doi',
    header: 'DOI',
    width: 30,
    format: 'hyperlink',
    enabled: false,
    order: 10,
  },
  {
    id: 'url',
    field: 'metadata.url',
    header: 'URL',
    width: 40,
    format: 'hyperlink',
    enabled: false,
    order: 11,
  },
  {
    id: 'isbn',
    field: 'metadata.isbn',
    header: 'ISBN',
    width: 20,
    format: 'text',
    enabled: false,
    order: 12,
  },
  {
    id: 'issn',
    field: 'metadata.issn',
    header: 'ISSN',
    width: 15,
    format: 'text',
    enabled: false,
    order: 13,
  },
  {
    id: 'abstract',
    field: 'metadata.abstract',
    header: 'Abstract',
    width: 80,
    format: 'text_wrap',
    enabled: false,
    order: 14,
  },
  {
    id: 'edition',
    field: 'metadata.edition',
    header: 'Edition',
    width: 15,
    format: 'text',
    enabled: false,
    order: 15,
  },
  {
    id: 'chapter',
    field: 'metadata.chapter',
    header: 'Chapter',
    width: 15,
    format: 'text',
    enabled: false,
    order: 16,
  },
  {
    id: 'editor',
    field: 'metadata.editor',
    header: 'Editor',
    width: 25,
    format: 'text',
    enabled: false,
    order: 17,
  },
  {
    id: 'series',
    field: 'metadata.series',
    header: 'Series',
    width: 25,
    format: 'text',
    enabled: false,
    order: 18,
  },
  {
    id: 'language',
    field: 'metadata.language',
    header: 'Language',
    width: 15,
    format: 'text',
    enabled: false,
    order: 19,
  },
  {
    id: 'tags',
    field: 'tags',
    header: 'Tags',
    width: 25,
    format: 'comma_separated',
    enabled: false,
    order: 20,
  },
  {
    id: 'annotation',
    field: 'annotations_all_content',
    header: 'Annotations',
    width: 80,
    format: 'text_wrap',
    enabled: false,
    order: 21,
  },
  {
    id: 'annotationType',
    field: 'annotations_all_types',
    header: 'Annotation Types',
    width: 20,
    format: 'text',
    enabled: false,
    order: 22,
  },
  {
    id: 'veritasScore',
    field: 'veritasScore.overallScore',
    header: 'Veritas Score',
    width: 12,
    format: 'veritas_score',
    enabled: false,
    order: 23,
  },
  {
    id: 'veritasLabel',
    field: 'veritasScore.label',
    header: 'Veritas Label',
    width: 15,
    format: 'text',
    enabled: false,
    order: 24,
  },
  {
    id: 'citationCount',
    field: 'metadata.citationCount',
    header: 'Citations',
    width: 12,
    format: 'number',
    enabled: false,
    order: 25,
  },
  {
    id: 'notes',
    field: 'notes',
    header: 'Notes',
    width: 50,
    format: 'text_wrap',
    enabled: false,
    order: 26,
  },
  {
    id: 'isFavorite',
    field: 'isFavorite',
    header: 'Favorite',
    width: 10,
    format: 'boolean',
    enabled: false,
    order: 27,
  },
  {
    id: 'createdAt',
    field: 'createdAt',
    header: 'Date Added',
    width: 15,
    format: 'date',
    enabled: false,
    order: 28,
  },
  {
    id: 'updatedAt',
    field: 'updatedAt',
    header: 'Last Modified',
    width: 15,
    format: 'date',
    enabled: false,
    order: 29,
  },
]

export function getPresetById(id: string): ExcelExportPreset | undefined {
  return systemPresets.find((p) => p.id === id)
}
