steps:
  - name: 'node:24'
    id: 'install'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        corepack enable
        corepack prepare --activate
        pnpm install --frozen-lockfile
    volumes:
      - name: 'pnpm-store'
        path: /root/.local/share/pnpm/store

  - name: 'gcr.io/cloud-builders/docker'
    id: 'pull-cache'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker pull ${_REGION}-docker.pkg.dev/${PROJECT_ID}/annobib/annobib-app:latest || true'
    waitFor: ['-']

  - name: 'node:24'
    id: 'lint'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'corepack enable && pnpm run lint'
    waitFor: ['install']

  - name: 'node:24'
    id: 'typecheck'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'corepack enable && pnpm run typecheck'
    waitFor: ['install']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    args:
      - 'build'
      - '-f'
      - 'infra/docker/Dockerfile'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/annobib/annobib-preview:pr-${_PR_NUMBER}'
      - '--cache-from'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/annobib/annobib-app:latest'
      - '--build-arg'
      - 'BUILDKIT_INLINE_CACHE=1'
      - '.'
    env:
      - 'DOCKER_BUILDKIT=1'
    waitFor: ['pull-cache']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-push'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/annobib/annobib-preview:pr-${_PR_NUMBER}'
    waitFor: ['docker-build', 'lint', 'typecheck']

  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'create-namespace'
    args:
      - 'create'
      - 'namespace'
      - 'preview-pr-${_PR_NUMBER}'
      - '--dry-run=client'
      - '-o'
      - 'yaml'
      - '|'
      - 'kubectl'
      - 'apply'
      - '-f'
      - '-'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_PREVIEW_CLUSTER}'
    waitFor: ['docker-push']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'generate-kustomization'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mkdir -p /workspace/infra/k8s/overlays/preview-pr-${_PR_NUMBER}
        cat > /workspace/infra/k8s/overlays/preview-pr-${_PR_NUMBER}/kustomization.yaml << EOF
        apiVersion: kustomize.config.k8s.io/v1beta1
        kind: Kustomization
        namespace: preview-pr-${_PR_NUMBER}
        resources:
          - ../../base
        patches:
          - patch: |-
              - op: replace
                path: /spec/replicas
                value: 1
            target:
              kind: Deployment
              name: annobib-app
          - patch: |-
              - op: replace
                path: /spec/rules/0/host
                value: pr-${_PR_NUMBER}.preview.annobib.com
            target:
              kind: Ingress
              name: annobib-ingress
        images:
          - name: annobib-app
            newName: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/annobib/annobib-preview
            newTag: pr-${_PR_NUMBER}
        configMapGenerator:
          - name: annobib-config
            behavior: merge
            literals:
              - NUXT_PUBLIC_APP_URL=https://pr-${_PR_NUMBER}.preview.annobib.com
              - NODE_ENV=preview
        EOF
    waitFor: ['create-namespace']

  - name: 'gcr.io/cloud-builders/gke-deploy'
    id: 'deploy-preview'
    args:
      - 'run'
      - '--filename=/workspace/infra/k8s/overlays/preview-pr-${_PR_NUMBER}'
      - '--location=${_REGION}'
      - '--cluster=${_PREVIEW_CLUSTER}'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
    waitFor: ['generate-kustomization']

  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'wait-deployment'
    args:
      - 'rollout'
      - 'status'
      - 'deployment/annobib-app'
      - '-n'
      - 'preview-pr-${_PR_NUMBER}'
      - '--timeout=300s'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_PREVIEW_CLUSTER}'
    waitFor: ['deploy-preview']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'post-comment'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        curl -X POST \
          -H "Authorization: token $$GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${_GITHUB_REPO}/issues/${_PR_NUMBER}/comments" \
          -d "{\"body\": \"Preview environment deployed!\\n\\n**URL:** https://pr-${_PR_NUMBER}.preview.annobib.com\\n\\nThis preview will be automatically deleted when the PR is closed.\"}"
    secretEnv: ['GITHUB_TOKEN']
    waitFor: ['wait-deployment']

substitutions:
  _REGION: 'us-central1'
  _PREVIEW_CLUSTER: 'annobib-preview-gke'
  _PR_NUMBER: ''
  _GITHUB_REPO: ''

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/github-token/versions/latest
      env: 'GITHUB_TOKEN'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'DOCKER_BUILDKIT=1'

timeout: '1200s'
