steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'pull-image'
    args:
      - 'pull'
      - '${_REGION}-docker.pkg.dev/${_STAGING_PROJECT_ID}/${_APP_NAME}/${_APP_NAME}-app:${TAG_NAME}'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'retag-image'
    args:
      - 'tag'
      - '${_REGION}-docker.pkg.dev/${_STAGING_PROJECT_ID}/${_APP_NAME}/${_APP_NAME}-app:${TAG_NAME}'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_APP_NAME}/${_APP_NAME}-app:${TAG_NAME}'
    waitFor: ['pull-image']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_APP_NAME}/${_APP_NAME}-app:${TAG_NAME}'
    waitFor: ['retag-image']

  - name: '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_APP_NAME}/${_APP_NAME}-app:${TAG_NAME}'
    id: 'migrate-production'
    dir: '/app'
    entrypoint: './node_modules/.bin/tsx'
    args: ['scripts/db/migrate.ts', 'up']
    env:
      - 'DATABASE_URL=${_PROD_DATABASE_URL}'
    waitFor: ['push-image']

  - name: '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_APP_NAME}/${_APP_NAME}-app:${TAG_NAME}'
    id: 'validate-migrations'
    dir: '/app'
    entrypoint: './node_modules/.bin/tsx'
    args: ['scripts/db/migrate.ts', 'validate']
    env:
      - 'DATABASE_URL=${_PROD_DATABASE_URL}'
    waitFor: ['migrate-production']

  - name: 'gcr.io/cloud-builders/gke-deploy'
    id: 'deploy-production'
    args:
      - 'run'
      - '--filename=infra/k8s/overlays/production'
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_APP_NAME}/${_APP_NAME}-app:${TAG_NAME}'
      - '--location=${_REGION}'
      - '--cluster=${_PROD_CLUSTER}'
    waitFor: ['validate-migrations']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'

substitutions:
  _REGION: 'us-central1'
  _APP_NAME: 'annobib'
  _STAGING_PROJECT_ID: 'annobib-staging'
  _PROD_CLUSTER: 'annobib-production-gke'
  _PROD_DATABASE_URL: ''

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '900s'

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_APP_NAME}/${_APP_NAME}-app:${TAG_NAME}'
