steps:
  - name: 'node:24'
    id: 'install'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'corepack enable && pnpm install --frozen-lockfile'

  - name: 'node:24'
    id: 'lint'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'corepack enable && pnpm run lint || echo "Lint warnings found (non-blocking)"'
    waitFor: ['install']

  - name: 'node:24'
    id: 'typecheck'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'corepack enable && pnpm run typecheck'
    waitFor: ['install']

  - name: 'node:24'
    id: 'test-unit'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'corepack enable && pnpm run test:unit'
    waitFor: ['install']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    args:
      - 'build'
      - '-f'
      - 'infra/docker/Dockerfile'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_APP_NAME}/${_APP_NAME}-app:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_APP_NAME}/${_APP_NAME}-app:latest'
      - '--cache-from'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_APP_NAME}/${_APP_NAME}-app:latest'
      - '.'
    waitFor: ['lint', 'typecheck', 'test-unit']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-push'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_APP_NAME}/${_APP_NAME}-app'
    waitFor: ['docker-build']

  - name: 'alpine:3'
    id: 'download-sql-proxy'
    entrypoint: 'sh'
    args:
      - '-c'
      - 'wget -q -O /workspace/cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.21.0/cloud-sql-proxy.linux.amd64 && chmod +x /workspace/cloud-sql-proxy'
    waitFor: ['-']

  - name: '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_APP_NAME}/${_APP_NAME}-app:${SHORT_SHA}'
    id: 'migrate-staging'
    dir: '/app'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        /workspace/cloud-sql-proxy ${_CLOUD_SQL_CONNECTION} --port 5433 &
        sleep 3
        ./node_modules/.bin/tsx scripts/db/migrate.ts up
        RESULT=$$?
        kill $$(pgrep cloud-sql-proxy) 2>/dev/null || true
        exit $$RESULT
    secretEnv: ['DATABASE_URL']
    env:
      - 'HOME=/tmp'
    waitFor: ['docker-push', 'download-sql-proxy']

  - name: '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_APP_NAME}/${_APP_NAME}-app:${SHORT_SHA}'
    id: 'validate-migrations'
    dir: '/app'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        /workspace/cloud-sql-proxy ${_CLOUD_SQL_CONNECTION} --port 5433 &
        sleep 3
        ./node_modules/.bin/tsx scripts/db/migrate.ts validate
        RESULT=$$?
        kill $$(pgrep cloud-sql-proxy) 2>/dev/null || true
        exit $$RESULT
    secretEnv: ['DATABASE_URL']
    env:
      - 'HOME=/tmp'
    waitFor: ['migrate-staging']

  - name: 'gcr.io/cloud-builders/gke-deploy'
    id: 'deploy-staging'
    args:
      - 'run'
      - '--filename=infra/k8s/overlays/staging'
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_APP_NAME}/${_APP_NAME}-app:${SHORT_SHA}'
      - '--location=${_STAGING_ZONE}'
      - '--cluster=${_STAGING_CLUSTER}'
    waitFor: ['validate-migrations']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_STAGING_ZONE}'

  - name: 'node:24'
    id: 'test-e2e'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'corepack enable && pnpm run test:e2e'
    env:
      - 'BASE_URL=${_STAGING_URL}'
    waitFor: ['deploy-staging']

substitutions:
  _REGION: 'us-central1'
  _STAGING_ZONE: 'us-central1-a'
  _APP_NAME: 'annobib'
  _STAGING_CLUSTER: 'annobib-staging-gke'
  _STAGING_URL: ''
  _CLOUD_SQL_CONNECTION: 'annobib-staging:us-central1:annobib-staging-db'

availableSecrets:
  secretManager:
    - versionName: projects/annobib-staging/secrets/staging-database-url/versions/latest
      env: 'DATABASE_URL'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1800s'

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_APP_NAME}/${_APP_NAME}-app:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_APP_NAME}/${_APP_NAME}-app:latest'
